"""Seed movies table with real MovieLens titles aligned to ML artifact IDs."""

from __future__ import annotations

import json
from pathlib import Path

from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.movie import Movie

SCRIPTS_DIR = Path(__file__).resolve().parent
SEED_DATA_PATH = SCRIPTS_DIR / "movielens_seed_data.json"


async def seed_movies(session: AsyncSession, max_movies: int = 1000) -> int:
    count_result = await session.execute(select(func.count()).select_from(Movie))
    if int(count_result.scalar_one()) >= max_movies:
        return 0

    movies: list[dict] = []

    if SEED_DATA_PATH.exists():
        # Use real MovieLens titles generated by ml/scripts/export_seed_data.py
        records = json.loads(SEED_DATA_PATH.read_text())
        for rec in records[:max_movies]:
            movies.append({
                "id":              rec["id"],
                "tmdb_id":         10_000_000 + rec["id"],
                "title":           rec["title"],
                "overview":        rec.get("overview", f"{rec['title']} — a film from the MovieLens catalog."),
                "poster_path":     rec.get("poster_path"),
                "backdrop_path":   rec.get("backdrop_path"),
                "release_year":    rec.get("release_year", 2000),
                "runtime_minutes": rec.get("runtime_minutes", 110),
                "maturity_rating": rec.get("maturity_rating", "PG-13"),
                "vote_average":    rec.get("vote_average", 7.0),
                "genres":          rec.get("genres", ["Drama"]),
                "popularity_score": float(rec.get("popularity_score", 500.0)),
            })
    else:
        # Fallback: curated demo titles for development without real data
        CURATED = {
            1: {"title": "The Matrix",          "overview": "A hacker discovers the truth about reality.",              "release_year": 1999, "genres": ["Sci-Fi", "Action"],    "vote_average": 8.7, "maturity_rating": "R",     "runtime_minutes": 136},
            2: {"title": "Arrival",             "overview": "A linguist races to communicate with alien visitors.",      "release_year": 2016, "genres": ["Sci-Fi", "Drama"],     "vote_average": 7.9, "maturity_rating": "PG-13", "runtime_minutes": 116},
            3: {"title": "Parasite",            "overview": "Class tension erupts inside an elegant modern home.",       "release_year": 2019, "genres": ["Thriller", "Drama"],   "vote_average": 8.5, "maturity_rating": "R",     "runtime_minutes": 132},
            4: {"title": "Mad Max: Fury Road",  "overview": "A desert chase becomes a fight for survival.",             "release_year": 2015, "genres": ["Action"],             "vote_average": 8.1, "maturity_rating": "R",     "runtime_minutes": 120},
            5: {"title": "Spirited Away",       "overview": "A girl enters a spirit world to save her parents.",        "release_year": 2001, "genres": ["Animation", "Fantasy"], "vote_average": 8.6, "maturity_rating": "PG",    "runtime_minutes": 125},
            6: {"title": "The Social Network",  "overview": "Ambition and betrayal surround Facebook's founding.",      "release_year": 2010, "genres": ["Drama"],              "vote_average": 7.8, "maturity_rating": "PG-13", "runtime_minutes": 120},
            7: {"title": "Inception",           "overview": "A thief enters dreams to plant an idea.",                  "release_year": 2010, "genres": ["Sci-Fi", "Action"],    "vote_average": 8.8, "maturity_rating": "PG-13", "runtime_minutes": 148},
            8: {"title": "Interstellar",        "overview": "Explorers travel through a wormhole to save humanity.",    "release_year": 2014, "genres": ["Sci-Fi", "Drama"],     "vote_average": 8.6, "maturity_rating": "PG-13", "runtime_minutes": 169},
            9: {"title": "The Dark Knight",     "overview": "Batman faces the Joker in Gotham.",                        "release_year": 2008, "genres": ["Action", "Crime"],     "vote_average": 9.0, "maturity_rating": "PG-13", "runtime_minutes": 152},
           10: {"title": "Pulp Fiction",        "overview": "Intersecting crime stories in Los Angeles.",               "release_year": 1994, "genres": ["Crime", "Drama"],      "vote_average": 8.9, "maturity_rating": "R",     "runtime_minutes": 154},
        }
        for mid in range(1, min(max_movies, 200) + 1):
            if mid in CURATED:
                data = CURATED[mid]
            else:
                year = 1985 + (mid % 35)
                genres = [["Action"], ["Drama"], ["Comedy"], ["Sci-Fi"], ["Thriller"]][mid % 5]
                data = {
                    "title": f"Kino Pick {mid}",
                    "overview": f"A compelling story from the Kino catalog (#{mid}).",
                    "release_year": year, "genres": genres,
                    "vote_average": 7.0 + (mid % 20) / 10,
                    "maturity_rating": "PG-13", "runtime_minutes": 110 + (mid % 40),
                }
            movies.append({
                "id":              mid,
                "tmdb_id":         10000 + mid,
                "title":           data["title"],
                "overview":        data["overview"],
                "poster_path":     data.get("poster_path"),
                "backdrop_path":   data.get("backdrop_path"),
                "release_year":    data["release_year"],
                "runtime_minutes": data.get("runtime_minutes", 120),
                "maturity_rating": data.get("maturity_rating", "PG-13"),
                "vote_average":    data.get("vote_average", 7.5),
                "genres":          data["genres"],
                "popularity_score": float(1000 - mid),
            })

    BATCH_SIZE = 2500
    for i in range(0, len(movies), BATCH_SIZE):
        batch = movies[i : i + BATCH_SIZE]
        stmt = insert(Movie).values(batch)
        stmt = stmt.on_conflict_do_nothing(index_elements=["id"])
        await session.execute(stmt)
    await session.commit()
    return len(movies)
