import type { ContentRowData, Movie } from "@/lib/types"

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: "The Matrix",
    overview: "A hacker discovers the truth about reality and joins a rebellion against machine control.",
    posterPath: null,
    backdropPath: null,
    releaseYear: 1999,
    genres: ["Sci-Fi", "Action"],
    matchPercent: 98,
    duration: "2h 16m",
    maturityRating: "R",
    voteAverage: 8.7,
  },
  {
    id: 2,
    title: "Arrival",
    overview: "A linguist races to understand mysterious visitors before global tension becomes war.",
    posterPath: null,
    backdropPath: null,
    releaseYear: 2016,
    genres: ["Sci-Fi", "Drama"],
    matchPercent: 96,
    duration: "1h 56m",
    maturityRating: "PG-13",
    voteAverage: 7.9,
  },
  {
    id: 3,
    title: "Parasite",
    overview: "A poor family infiltrates a wealthy household, exposing class conflict with escalating force.",
    posterPath: null,
    backdropPath: null,
    releaseYear: 2019,
    genres: ["Thriller", "Drama"],
    matchPercent: 94,
    duration: "2h 12m",
    maturityRating: "R",
    voteAverage: 8.5,
  },
  {
    id: 4,
    title: "Mad Max: Fury Road",
    overview: "A desert chase becomes a breakneck fight for survival and freedom.",
    posterPath: null,
    backdropPath: null,
    releaseYear: 2015,
    genres: ["Action"],
    matchPercent: 92,
    duration: "2h",
    maturityRating: "R",
    voteAverage: 8.1,
  },
  {
    id: 5,
    title: "Spirited Away",
    overview: "A girl enters a spirit world and must find courage to save her parents.",
    posterPath: null,
    backdropPath: null,
    releaseYear: 2001,
    genres: ["Animation", "Fantasy"],
    matchPercent: 91,
    duration: "2h 5m",
    maturityRating: "PG",
    voteAverage: 8.6,
  },
  {
    id: 6,
    title: "The Social Network",
    overview: "Ambition, betrayal, and invention collide around the founding of Facebook.",
    posterPath: null,
    backdropPath: null,
    releaseYear: 2010,
    genres: ["Drama"],
    matchPercent: 89,
    duration: "2h",
    maturityRating: "PG-13",
    voteAverage: 7.8,
  },
]

const extendedMock: Movie[] = [...mockMovies, ...mockMovies, ...mockMovies, ...mockMovies].map(
  (movie, index) => ({ ...movie, id: movie.id + index * 10 }),
)

export const mockRows: ContentRowData[] = [
  { id: "trending", title: "Trending Now", movies: mockMovies, variant: "standard" },
  { id: "top10", title: "Top 10 Movies in Your Region Today", movies: extendedMock.slice(0, 10), variant: "top10" },
  { id: "picks", title: "Top Picks for You", movies: [...mockMovies].reverse(), variant: "standard" },
  { id: "continue", title: "Continue Watching", movies: mockMovies.slice(0, 4), variant: "continue-watching" },
  { id: "discover", title: "Discover Something New", movies: extendedMock, variant: "standard" },
]
